// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixHelloWorldCommandButton
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAppFastTrackPackageString = "f689a0bb-90d5-4ef2-aaa0-fe8ec6b0dc3c";
        public const string guidAppFastTrackPackageCmdSetString = "68401c87-1520-4f76-83f2-96c17022f744";
        public const string guidImagesString = "ceb94490-5956-4313-8a19-4def111454e6";
        public static Guid guidAppFastTrackPackage = new Guid(guidAppFastTrackPackageString);
        public static Guid guidAppFastTrackPackageCmdSet = new Guid(guidAppFastTrackPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AppFastTrackId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
