// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixHelloWorldCommandButton
{
    static class Vsix
    {
        public const string Id = "VsixHelloWorldCommandButton.5f3bb123-e2dd-458b-bdcf-39784e50c864";
        public const string Name = "VsixHelloWorldCommandButton";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Greg Trevellick";
        public const string Tags = "";
    }
}
